# Generated by Django 5.1.3 on 2024-12-10 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_game_buyer'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок новости', max_length=30)),
                ('content', models.TextField(help_text='Содержание новости')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
